######################################################################
# Automatically generated by qmake (1.07a) Wed May 13 13:28:33 2020
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += arm.h visual.h
SOURCES += arm.cpp main.cpp visual.cpp
TRANSLATIONS += arm_ru.ts main_ru.ts
