######################################################################
# Automatically generated by qmake (1.07a) Mon May 11 20:23:47 2020
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += arm.h visual.h
SOURCES += arm.cpp main.cpp visual.cpp
TRANSLATIONS += arm_ru.ts main_ru.ts
