#############################################################################
# Makefile for building: diplom
# Generated by qmake (1.07a) (Qt 3.3.3) on: Thu May 14 00:22:52 2020
# Project:  diplom.pro
# Template: app
# Command: $(QMAKE) -o Makefile diplom.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -D_REENTRANT -Wall -W  -DQT_NO_DEBUG
CXXFLAGS = -pipe -D_REENTRANT -Wall -W  -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/lib/qt-3.3.3/mkspecs/default -I. -I. -I$(QTDIR)/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -rf
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -rf
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = arm.h \
		visual.h
SOURCES = arm.cpp \
		main.cpp \
		visual.cpp
OBJECTS = arm.o \
		main.o \
		visual.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_arm.cpp \
		moc_visual.cpp
OBJMOC = moc_arm.o \
		moc_visual.o
DIST	   = diplom.pro
QMAKE_TARGET = diplom
DESTDIR  = 
TARGET   = diplom

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

initScript:
postScript:
all:  initScript  Makefile $(TARGET)  postScript 

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: diplom.pro  /usr/lib/qt-3.3.3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile diplom.pro
qmake: 
	@$(QMAKE) -o Makefile diplom.pro

dist: 
	@mkdir -p .tmp/diplom && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/diplom/ && $(COPY_FILE) --parents arm_ru.ts main_ru.ts .tmp/diplom/ && ( cd `dirname .tmp/diplom` && $(TAR) diplom.tar diplom && $(GZIP) diplom.tar ) && $(MOVE) `dirname .tmp/diplom`/diplom.tar.gz . && $(DEL_FILE) -r .tmp/diplom

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

arm.o: arm.cpp arm.h \
		visual.h

main.o: main.cpp arm.h \
		visual.h

visual.o: visual.cpp visual.h

moc_arm.o: moc_arm.cpp  arm.h visual.h

moc_visual.o: moc_visual.cpp  visual.h 

moc_arm.cpp: $(MOC) arm.h
	$(MOC) arm.h -o moc_arm.cpp

moc_visual.cpp: $(MOC) visual.h
	$(MOC) visual.h -o moc_visual.cpp

####### Install

install:  

uninstall:  

